env: "local" #local,dev,prod  //// НУЖНЫ ПРОБЕЛЫ
storage_path: "./storage/storage.db"
http_server :
  address: "localhost:8082"
  timeout: 4s
  idle_timeoutz: 60s
  user: "myuser"
  password: "mypass"